# Generated by Django 3.2.2 on 2021-06-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the vehicle make', max_length=50)),
                ('website', models.URLField(help_text='The official website for this vehicle make')),
            ],
        ),
    ]
