# Generated by Django 3.2.2 on 2021-06-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the vehicle model', max_length=100)),
                ('year', models.IntegerField(help_text='The model year for this model')),
            ],
        ),
    ]
