# Generated by Django 3.2.2 on 2021-07-04 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blweb', '0006_alter_profile_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default=None, help_text='The name of this vehicle configuration', max_length=200)),
                ('make', models.ForeignKey(default=None, help_text='The vehicle make associated with this build', on_delete=django.db.models.deletion.CASCADE, to='blweb.vehiclemake')),
                ('model', models.ForeignKey(default=None, help_text='The vehicle model associated with this option package', on_delete=django.db.models.deletion.CASCADE, to='blweb.vehiclemodel')),
                ('options', models.ManyToManyField(help_text='List of options selected in this config', to='blweb.VehicleOption')),
                ('user', models.ForeignKey(default=None, help_text='The user associated with this vehicle configuration', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
