# Generated by Django 3.2.2 on 2021-07-04 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blweb', '0008_alter_vehicleconfig_config_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleconfig',
            name='model',
            field=models.ForeignKey(blank=True, default=None, help_text='The vehicle model associated with this option package', null=True, on_delete=django.db.models.deletion.CASCADE, to='blweb.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='vehicleconfig',
            name='options',
            field=models.ManyToManyField(blank=True, help_text='List of options selected in this config', null=True, to='blweb.VehicleOption'),
        ),
        migrations.AlterField(
            model_name='vehicleconfig',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='The user associated with this vehicle configuration', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
