# Generated by Django 3.2.2 on 2021-07-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blweb', '0009_auto_20210704_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleconfig',
            name='options',
            field=models.ManyToManyField(blank=True, help_text='List of options selected in this config', to='blweb.VehicleOption'),
        ),
    ]
