# Generated by Django 3.2.2 on 2021-08-01 14:41

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('blweb', '0013_vehiclemodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='The street address e.g. 123 Main St.', max_length=200)),
                ('zip_code', localflavor.us.models.USZipCodeField(help_text='The address Zip Code', max_length=10)),
                ('state', localflavor.us.models.USStateField(help_text='The address state e.g. PA', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='dealer_make',
            field=models.ForeignKey(blank=True, default=None, help_text='The vehicle make associated with this dealer', null=True, on_delete=django.db.models.deletion.CASCADE, to='blweb.vehiclemake'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(blank=True, default=None, help_text='The US mailing address associated with this account (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='blweb.address'),
        ),
    ]
