# Generated by Django 3.2.2 on 2021-08-01 17:56

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('blweb', '0014_auto_20210801_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='State College', help_text='The city for this address, e.g. Farmville', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=localflavor.us.models.USStateField(help_text='The address state, e.g. PA', max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(help_text='The street address, e.g. 123 Main St.', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(help_text='The address Zip Code, e.g. 90210', max_length=10),
        ),
    ]
